(cl:defpackage antobot_msgs-srv
  (:use )
  (:export
   "ANTOREC"
   "<ANTOREC-REQUEST>"
   "ANTOREC-REQUEST"
   "<ANTOREC-RESPONSE>"
   "ANTOREC-RESPONSE"
   "CAMMANAGER"
   "<CAMMANAGER-REQUEST>"
   "CAMMANAGER-REQUEST"
   "<CAMMANAGER-RESPONSE>"
   "CAMMANAGER-RESPONSE"
   "SOFTSHUTDOWN"
   "<SOFTSHUTDOWN-REQUEST>"
   "SOFTSHUTDOWN-REQUEST"
   "<SOFTSHUTDOWN-RESPONSE>"
   "SOFTSHUTDOWN-RESPONSE"
  ))

