// Generated by gencpp from file antobot_msgs/antoRec.msg
// DO NOT EDIT!


#ifndef ANTOBOT_MSGS_MESSAGE_ANTOREC_H
#define ANTOBOT_MSGS_MESSAGE_ANTOREC_H

#include <ros/service_traits.h>


#include <antobot_msgs/antoRecRequest.h>
#include <antobot_msgs/antoRecResponse.h>


namespace antobot_msgs
{

struct antoRec
{

typedef antoRecRequest Request;
typedef antoRecResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct antoRec
} // namespace antobot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::antobot_msgs::antoRec > {
  static const char* value()
  {
    return "d5a7288f1d26019f672552946e4bed3b";
  }

  static const char* value(const ::antobot_msgs::antoRec&) { return value(); }
};

template<>
struct DataType< ::antobot_msgs::antoRec > {
  static const char* value()
  {
    return "antobot_msgs/antoRec";
  }

  static const char* value(const ::antobot_msgs::antoRec&) { return value(); }
};


// service_traits::MD5Sum< ::antobot_msgs::antoRecRequest> should match
// service_traits::MD5Sum< ::antobot_msgs::antoRec >
template<>
struct MD5Sum< ::antobot_msgs::antoRecRequest>
{
  static const char* value()
  {
    return MD5Sum< ::antobot_msgs::antoRec >::value();
  }
  static const char* value(const ::antobot_msgs::antoRecRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::antobot_msgs::antoRecRequest> should match
// service_traits::DataType< ::antobot_msgs::antoRec >
template<>
struct DataType< ::antobot_msgs::antoRecRequest>
{
  static const char* value()
  {
    return DataType< ::antobot_msgs::antoRec >::value();
  }
  static const char* value(const ::antobot_msgs::antoRecRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::antobot_msgs::antoRecResponse> should match
// service_traits::MD5Sum< ::antobot_msgs::antoRec >
template<>
struct MD5Sum< ::antobot_msgs::antoRecResponse>
{
  static const char* value()
  {
    return MD5Sum< ::antobot_msgs::antoRec >::value();
  }
  static const char* value(const ::antobot_msgs::antoRecResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::antobot_msgs::antoRecResponse> should match
// service_traits::DataType< ::antobot_msgs::antoRec >
template<>
struct DataType< ::antobot_msgs::antoRecResponse>
{
  static const char* value()
  {
    return DataType< ::antobot_msgs::antoRec >::value();
  }
  static const char* value(const ::antobot_msgs::antoRecResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ANTOBOT_MSGS_MESSAGE_ANTOREC_H
