// Generated by gencpp from file antobot_msgs/camManager.msg
// DO NOT EDIT!


#ifndef ANTOBOT_MSGS_MESSAGE_CAMMANAGER_H
#define ANTOBOT_MSGS_MESSAGE_CAMMANAGER_H

#include <ros/service_traits.h>


#include <antobot_msgs/camManagerRequest.h>
#include <antobot_msgs/camManagerResponse.h>


namespace antobot_msgs
{

struct camManager
{

typedef camManagerRequest Request;
typedef camManagerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct camManager
} // namespace antobot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::antobot_msgs::camManager > {
  static const char* value()
  {
    return "fc42ba797ab7c1398107c36a354e835f";
  }

  static const char* value(const ::antobot_msgs::camManager&) { return value(); }
};

template<>
struct DataType< ::antobot_msgs::camManager > {
  static const char* value()
  {
    return "antobot_msgs/camManager";
  }

  static const char* value(const ::antobot_msgs::camManager&) { return value(); }
};


// service_traits::MD5Sum< ::antobot_msgs::camManagerRequest> should match
// service_traits::MD5Sum< ::antobot_msgs::camManager >
template<>
struct MD5Sum< ::antobot_msgs::camManagerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::antobot_msgs::camManager >::value();
  }
  static const char* value(const ::antobot_msgs::camManagerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::antobot_msgs::camManagerRequest> should match
// service_traits::DataType< ::antobot_msgs::camManager >
template<>
struct DataType< ::antobot_msgs::camManagerRequest>
{
  static const char* value()
  {
    return DataType< ::antobot_msgs::camManager >::value();
  }
  static const char* value(const ::antobot_msgs::camManagerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::antobot_msgs::camManagerResponse> should match
// service_traits::MD5Sum< ::antobot_msgs::camManager >
template<>
struct MD5Sum< ::antobot_msgs::camManagerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::antobot_msgs::camManager >::value();
  }
  static const char* value(const ::antobot_msgs::camManagerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::antobot_msgs::camManagerResponse> should match
// service_traits::DataType< ::antobot_msgs::camManager >
template<>
struct DataType< ::antobot_msgs::camManagerResponse>
{
  static const char* value()
  {
    return DataType< ::antobot_msgs::camManager >::value();
  }
  static const char* value(const ::antobot_msgs::camManagerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ANTOBOT_MSGS_MESSAGE_CAMMANAGER_H
