// Generated by gencpp from file antobot_msgs/softShutdown.msg
// DO NOT EDIT!


#ifndef ANTOBOT_MSGS_MESSAGE_SOFTSHUTDOWN_H
#define ANTOBOT_MSGS_MESSAGE_SOFTSHUTDOWN_H

#include <ros/service_traits.h>


#include <antobot_msgs/softShutdownRequest.h>
#include <antobot_msgs/softShutdownResponse.h>


namespace antobot_msgs
{

struct softShutdown
{

typedef softShutdownRequest Request;
typedef softShutdownResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct softShutdown
} // namespace antobot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::antobot_msgs::softShutdown > {
  static const char* value()
  {
    return "f4f225f161cdec955f047b31d2533a97";
  }

  static const char* value(const ::antobot_msgs::softShutdown&) { return value(); }
};

template<>
struct DataType< ::antobot_msgs::softShutdown > {
  static const char* value()
  {
    return "antobot_msgs/softShutdown";
  }

  static const char* value(const ::antobot_msgs::softShutdown&) { return value(); }
};


// service_traits::MD5Sum< ::antobot_msgs::softShutdownRequest> should match
// service_traits::MD5Sum< ::antobot_msgs::softShutdown >
template<>
struct MD5Sum< ::antobot_msgs::softShutdownRequest>
{
  static const char* value()
  {
    return MD5Sum< ::antobot_msgs::softShutdown >::value();
  }
  static const char* value(const ::antobot_msgs::softShutdownRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::antobot_msgs::softShutdownRequest> should match
// service_traits::DataType< ::antobot_msgs::softShutdown >
template<>
struct DataType< ::antobot_msgs::softShutdownRequest>
{
  static const char* value()
  {
    return DataType< ::antobot_msgs::softShutdown >::value();
  }
  static const char* value(const ::antobot_msgs::softShutdownRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::antobot_msgs::softShutdownResponse> should match
// service_traits::MD5Sum< ::antobot_msgs::softShutdown >
template<>
struct MD5Sum< ::antobot_msgs::softShutdownResponse>
{
  static const char* value()
  {
    return MD5Sum< ::antobot_msgs::softShutdown >::value();
  }
  static const char* value(const ::antobot_msgs::softShutdownResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::antobot_msgs::softShutdownResponse> should match
// service_traits::DataType< ::antobot_msgs::softShutdown >
template<>
struct DataType< ::antobot_msgs::softShutdownResponse>
{
  static const char* value()
  {
    return DataType< ::antobot_msgs::softShutdown >::value();
  }
  static const char* value(const ::antobot_msgs::softShutdownResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ANTOBOT_MSGS_MESSAGE_SOFTSHUTDOWN_H
