// Generated by gencpp from file antobot_msgs/softShutdownResponse.msg
// DO NOT EDIT!


#ifndef ANTOBOT_MSGS_MESSAGE_SOFTSHUTDOWNRESPONSE_H
#define ANTOBOT_MSGS_MESSAGE_SOFTSHUTDOWNRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace antobot_msgs
{
template <class ContainerAllocator>
struct softShutdownResponse_
{
  typedef softShutdownResponse_<ContainerAllocator> Type;

  softShutdownResponse_()
    : responseBool(false)
    , responseString()  {
    }
  softShutdownResponse_(const ContainerAllocator& _alloc)
    : responseBool(false)
    , responseString(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _responseBool_type;
  _responseBool_type responseBool;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _responseString_type;
  _responseString_type responseString;





  typedef boost::shared_ptr< ::antobot_msgs::softShutdownResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::antobot_msgs::softShutdownResponse_<ContainerAllocator> const> ConstPtr;

}; // struct softShutdownResponse_

typedef ::antobot_msgs::softShutdownResponse_<std::allocator<void> > softShutdownResponse;

typedef boost::shared_ptr< ::antobot_msgs::softShutdownResponse > softShutdownResponsePtr;
typedef boost::shared_ptr< ::antobot_msgs::softShutdownResponse const> softShutdownResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::antobot_msgs::softShutdownResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::antobot_msgs::softShutdownResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::antobot_msgs::softShutdownResponse_<ContainerAllocator1> & lhs, const ::antobot_msgs::softShutdownResponse_<ContainerAllocator2> & rhs)
{
  return lhs.responseBool == rhs.responseBool &&
    lhs.responseString == rhs.responseString;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::antobot_msgs::softShutdownResponse_<ContainerAllocator1> & lhs, const ::antobot_msgs::softShutdownResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace antobot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::antobot_msgs::softShutdownResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::antobot_msgs::softShutdownResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::antobot_msgs::softShutdownResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::antobot_msgs::softShutdownResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::antobot_msgs::softShutdownResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::antobot_msgs::softShutdownResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::antobot_msgs::softShutdownResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64df45fda081ce59f91d7993b5be89f3";
  }

  static const char* value(const ::antobot_msgs::softShutdownResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64df45fda081ce59ULL;
  static const uint64_t static_value2 = 0xf91d7993b5be89f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::antobot_msgs::softShutdownResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "antobot_msgs/softShutdownResponse";
  }

  static const char* value(const ::antobot_msgs::softShutdownResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::antobot_msgs::softShutdownResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool responseBool\n"
"string responseString\n"
;
  }

  static const char* value(const ::antobot_msgs::softShutdownResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::antobot_msgs::softShutdownResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.responseBool);
      stream.next(m.responseString);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct softShutdownResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::antobot_msgs::softShutdownResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::antobot_msgs::softShutdownResponse_<ContainerAllocator>& v)
  {
    s << indent << "responseBool: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.responseBool);
    s << indent << "responseString: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.responseString);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANTOBOT_MSGS_MESSAGE_SOFTSHUTDOWNRESPONSE_H
