set(_CATKIN_CURRENT_PACKAGE "antobot_gps")
set(antobot_gps_VERSION "0.0.0")
set(antobot_gps_MAINTAINER "Ash-antobot <aswathi.muralidharan@antobot.ai>")
set(antobot_gps_PACKAGE_FORMAT "2")
set(antobot_gps_BUILD_DEPENDS "rospy" "std_msgs")
set(antobot_gps_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(antobot_gps_BUILDTOOL_DEPENDS "catkin")
set(antobot_gps_BUILDTOOL_EXPORT_DEPENDS )
set(antobot_gps_EXEC_DEPENDS "rospy" "std_msgs")
set(antobot_gps_RUN_DEPENDS "rospy" "std_msgs")
set(antobot_gps_TEST_DEPENDS )
set(antobot_gps_DOC_DEPENDS )
set(antobot_gps_URL_WEBSITE "")
set(antobot_gps_URL_BUGTRACKER "")
set(antobot_gps_URL_REPOSITORY "")
set(antobot_gps_DEPRECATED "")