set(_CATKIN_CURRENT_PACKAGE "ekf_tracker")
set(ekf_tracker_VERSION "0.0.0")
set(ekf_tracker_MAINTAINER "taie <taie@todo.todo>")
set(ekf_tracker_PACKAGE_FORMAT "2")
set(ekf_tracker_BUILD_DEPENDS "geometry_msgs" "nav_msgs" "rospy" "sensor_msgs" "std_msgs" "tf2_ros")
set(ekf_tracker_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "rospy" "sensor_msgs" "std_msgs" "tf2_ros")
set(ekf_tracker_BUILDTOOL_DEPENDS "catkin")
set(ekf_tracker_BUILDTOOL_EXPORT_DEPENDS )
set(ekf_tracker_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "rospy" "sensor_msgs" "std_msgs" "tf2_ros")
set(ekf_tracker_RUN_DEPENDS "geometry_msgs" "nav_msgs" "rospy" "sensor_msgs" "std_msgs" "tf2_ros")
set(ekf_tracker_TEST_DEPENDS )
set(ekf_tracker_DOC_DEPENDS )
set(ekf_tracker_URL_WEBSITE "")
set(ekf_tracker_URL_BUGTRACKER "")
set(ekf_tracker_URL_REPOSITORY "")
set(ekf_tracker_DEPRECATED "")