set(_CATKIN_CURRENT_PACKAGE "antobot_hmi")
set(antobot_hmi_VERSION "0.0.0")
set(antobot_hmi_MAINTAINER "Zhuang Zhou <zhuang.zhou@antobot.ai>")
set(antobot_hmi_PACKAGE_FORMAT "2")
set(antobot_hmi_BUILD_DEPENDS "roscpp" "rospy" "serial" "std_msgs")
set(antobot_hmi_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "serial" "std_msgs")
set(antobot_hmi_BUILDTOOL_DEPENDS "catkin")
set(antobot_hmi_BUILDTOOL_EXPORT_DEPENDS )
set(antobot_hmi_EXEC_DEPENDS "roscpp" "rospy" "serial" "std_msgs")
set(antobot_hmi_RUN_DEPENDS "roscpp" "rospy" "serial" "std_msgs")
set(antobot_hmi_TEST_DEPENDS )
set(antobot_hmi_DOC_DEPENDS )
set(antobot_hmi_URL_WEBSITE "")
set(antobot_hmi_URL_BUGTRACKER "")
set(antobot_hmi_URL_REPOSITORY "")
set(antobot_hmi_DEPRECATED "")