set(_CATKIN_CURRENT_PACKAGE "apf_navigator")
set(apf_navigator_VERSION "0.0.0")
set(apf_navigator_MAINTAINER "taie <taie@todo.todo>")
set(apf_navigator_PACKAGE_FORMAT "2")
set(apf_navigator_BUILD_DEPENDS "geometry_msgs" "rospy" "sensor_msgs" "std_msgs")
set(apf_navigator_BUILD_EXPORT_DEPENDS "geometry_msgs" "rospy" "sensor_msgs" "std_msgs")
set(apf_navigator_BUILDTOOL_DEPENDS "catkin")
set(apf_navigator_BUILDTOOL_EXPORT_DEPENDS )
set(apf_navigator_EXEC_DEPENDS "geometry_msgs" "rospy" "sensor_msgs" "std_msgs")
set(apf_navigator_RUN_DEPENDS "geometry_msgs" "rospy" "sensor_msgs" "std_msgs")
set(apf_navigator_TEST_DEPENDS )
set(apf_navigator_DOC_DEPENDS )
set(apf_navigator_URL_WEBSITE "")
set(apf_navigator_URL_BUGTRACKER "")
set(apf_navigator_URL_REPOSITORY "")
set(apf_navigator_DEPRECATED "")