set(_CATKIN_CURRENT_PACKAGE "vision_yolo")
set(vision_yolo_VERSION "0.0.0")
set(vision_yolo_MAINTAINER "taie <taie@todo.todo>")
set(vision_yolo_PACKAGE_FORMAT "2")
set(vision_yolo_BUILD_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(vision_yolo_BUILD_EXPORT_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(vision_yolo_BUILDTOOL_DEPENDS "catkin")
set(vision_yolo_BUILDTOOL_EXPORT_DEPENDS )
set(vision_yolo_EXEC_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(vision_yolo_RUN_DEPENDS "cv_bridge" "rospy" "sensor_msgs" "std_msgs")
set(vision_yolo_TEST_DEPENDS )
set(vision_yolo_DOC_DEPENDS )
set(vision_yolo_URL_WEBSITE "")
set(vision_yolo_URL_BUGTRACKER "")
set(vision_yolo_URL_REPOSITORY "")
set(vision_yolo_DEPRECATED "")