set(_CATKIN_CURRENT_PACKAGE "imu_bno055")
set(imu_bno055_VERSION "2.0.0")
set(imu_bno055_MAINTAINER "dheera <dheera@dheera.net>")
set(imu_bno055_PACKAGE_FORMAT "3")
set(imu_bno055_BUILD_DEPENDS "ros_environment" "sensor_msgs" "std_msgs" "std_srvs")
set(imu_bno055_BUILD_EXPORT_DEPENDS )
set(imu_bno055_BUILDTOOL_DEPENDS "catkin")
set(imu_bno055_BUILDTOOL_EXPORT_DEPENDS )
set(imu_bno055_EXEC_DEPENDS )
set(imu_bno055_RUN_DEPENDS )
set(imu_bno055_TEST_DEPENDS )
set(imu_bno055_DOC_DEPENDS )
set(imu_bno055_URL_WEBSITE "")
set(imu_bno055_URL_BUGTRACKER "")
set(imu_bno055_URL_REPOSITORY "")
set(imu_bno055_DEPRECATED "")