# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/taie/Desktop/Antobot/src/zed_interfaces/msg/BoundingBox2Df.msg;/home/taie/Desktop/Antobot/src/zed_interfaces/msg/BoundingBox2Di.msg;/home/taie/Desktop/Antobot/src/zed_interfaces/msg/BoundingBox3D.msg;/home/taie/Desktop/Antobot/src/zed_interfaces/msg/Keypoint2Df.msg;/home/taie/Desktop/Antobot/src/zed_interfaces/msg/Keypoint2Di.msg;/home/taie/Desktop/Antobot/src/zed_interfaces/msg/Keypoint3D.msg;/home/taie/Desktop/Antobot/src/zed_interfaces/msg/Object.msg;/home/taie/Desktop/Antobot/src/zed_interfaces/msg/ObjectsStamped.msg;/home/taie/Desktop/Antobot/src/zed_interfaces/msg/Skeleton2D.msg;/home/taie/Desktop/Antobot/src/zed_interfaces/msg/Skeleton3D.msg;/home/taie/Desktop/Antobot/src/zed_interfaces/msg/RGBDSensors.msg;/home/taie/Desktop/Antobot/src/zed_interfaces/msg/PlaneStamped.msg;/home/taie/Desktop/Antobot/src/zed_interfaces/msg/PosTrackStatus.msg"
services_str = "/home/taie/Desktop/Antobot/src/zed_interfaces/srv/set_pose.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/reset_odometry.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/reset_tracking.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/start_svo_recording.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/stop_svo_recording.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/start_remote_stream.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/stop_remote_stream.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/set_led_status.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/toggle_led.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/start_3d_mapping.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/stop_3d_mapping.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/save_3d_map.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/start_object_detection.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/stop_object_detection.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/save_area_memory.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/set_roi.srv;/home/taie/Desktop/Antobot/src/zed_interfaces/srv/reset_roi.srv"
pkg_name = "zed_interfaces"
dependencies_str = "std_msgs;geometry_msgs;sensor_msgs;shape_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "zed_interfaces;/home/taie/Desktop/Antobot/src/zed_interfaces/msg;std_msgs;/opt/ros/noetic/share/std_msgs/cmake/../msg;geometry_msgs;/opt/ros/noetic/share/geometry_msgs/cmake/../msg;sensor_msgs;/opt/ros/noetic/share/sensor_msgs/cmake/../msg;shape_msgs;/opt/ros/noetic/share/shape_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python3"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/noetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
